### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by gekomod** [pirasterize/sonata-form-builder#31]
`Problem 1
    - Can only install one of: symfony/swiftmailer-bundle[2.6.x-dev, v3.2.8].
    - Can only install one of: symfony/swiftmailer-bundle[v3.2.8, 2.6.x-dev].
    - Can only install one of: symfony/swiftmailer-bundle[2.6.x-dev, v3.2.8].
    - pirasterize/sonata-form-builder dev-master requires symfony/swiftmailer-bundle ^2.6.4 -> satisfiable by symfony/swiftmailer-bundle[2.6.x-dev].
    - Installation request for pirasterize/sonata-form-builder dev-master -> satisfiable by pirasterize/sonata-form-builder[dev-master].
    - Installation request for symfony/swiftmailer-bundle (locked at v3.2.8, required as ^3.2) -> satisfiable by symfony/swiftmailer-bundle[v3.2.8].`

Swiftmailer 3.2.8, symfony 4.3, cant install this package

**Comment by pix-art** [comment]
Fixed in latest merge
